version: '3.8'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: foodServiceDB
    container_name: portfolioDB
    volumes:
      - ./mongo:/data/db

  portfolioserverapp:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    container_name: PortfolioServer
    restart: always
    ports:
      - "${PORT}:${PORT}"

    environment:
      STATE: ${STATE}
      PORT: ${PORT}
      EMAIL: ${EMAIL}
      EPASSWORD: ${EPASSWORD}
      EMAILTO: ${EMAILTO}
      MONGODB: ${MONGODB}
      JWT_SECRET: ${JWT_SECRET}
      HOST_API: ${HOST_API}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}